import { Course, Module, Lesson, LessonContent, Resource } from './types';

// CATÁLOGO 2026
export const COURSES_2026: Course[] = [
  // 1. AUTOCAD 2D 2026
  {
    id: 'autocad-2d-2026',
    slug: 'autocad-2d-2026',
    version: '2026',
    software: 'AutoCAD 2026',
    title: 'AutoCAD 2D 2026 - Nivel Básico',
    subtitle: 'Domina el diseño técnico 2D con la última versión de AutoCAD',
    category: 'AutoCAD',
    level: 'Básico',
    duration: 24,
    sessions: 8,
    description: `Curso completo de AutoCAD 2D 2026 desde cero. Aprende todas las novedades de la versión 2026 incluyendo:
    
    • Nuevas herramientas de dibujo inteligente
    • Interfaz optimizada AutoCAD 2026
    • Integración mejorada con AutoCAD Web
    • Nuevos comandos de productividad
    • Smart dimensioning mejorado
    • Colaboración en tiempo real
    
    Certificación Autodesk oficial al finalizar.`,
    objectives: [
      'Dominar la interfaz de AutoCAD 2026 y sus nuevas funcionalidades',
      'Crear dibujos 2D precisos con herramientas avanzadas',
      'Aplicar las nuevas características de layers y bloques dinámicos',
      'Generar layouts profesionales y plotear con calidad de impresión',
      'Utilizar las herramientas de colaboración de AutoCAD 2026',
      'Prepararse para certificación Autodesk Certified User',
    ],
    prerequisites: [
      'Conocimientos básicos de Windows 10/11',
      'Conceptos fundamentales de dibujo técnico',
      'Computadora con 8GB RAM mínimo (AutoCAD 2026 requirements)',
    ],
    certification: 'Autodesk Certified User - AutoCAD 2026',
    instructor: 'Ing. [Nombre] - Autodesk Certified Instructor',
    price: 299,
    priceVEF: 11000,
    image: '/images/courses/autocad-2d-2026-hero.jpg',
    thumbnail: '/images/courses/autocad-2d-2026-thumb.jpg',
    featured: true,
    popular: true,
    enrollmentCount: 0,
    rating: 0,
    reviewsCount: 0,
    skills: ['AutoCAD 2D', 'Dibujo Técnico', 'CAD 2026', 'Planos', 'Drafting'],
    tags: ['AutoCAD', '2026', '2D', 'Diseño', 'Certificación', 'Básico', 'Nuevo'],
    lastUpdated: '2026-01-15T00:00:00Z',
    releaseDate: '2025-11-01T00:00:00Z',
    syllabus: [
      {
        id: 'mod-1',
        number: 1,
        title: 'Módulo 1: Introducción e Interfaz 2026',
        description: 'Navegación, gestión de archivos y novedades de la interfaz 2026.',
        duration: 3,
        order: 1,
        lessons: [
          {
            id: 'lec-1-1',
            moduleId: 'mod-1',
            number: 1,
            title: 'Interfaz y Espacio de Trabajo 2026',
            description: 'Exploración de la nueva interfaz optimizada y personalización.',
            duration: 30,
            type: 'video',
            order: 1,
            content: {
              videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
              richText: `<h2>Interfaz AutoCAD 2026</h2>
              <p>La nueva interfaz de AutoCAD 2026 está diseñada para maximizar el área de dibujo y facilitar el acceso a herramientas inteligentes.</p>`,
            },
            resources: [],
          },
        ],
      },
      { id: 'mod-2', number: 2, title: 'Módulo 2: Dibujo y Precisión', description: 'Herramientas fundamentales de dibujo y ayudas de precisión.', duration: 4, order: 2, lessons: [] },
      { id: 'mod-3', number: 3, title: 'Módulo 3: Edición y Organización', description: 'Modificación de geometría y organización por capas.', duration: 5, order: 3, lessons: [] },
      { id: 'mod-4', number: 4, title: 'Módulo 4: Bloques Inteligentes e IA', description: 'Uso de Smart Blocks y asistentes de IA en AutoCAD 2026.', duration: 4, order: 4, lessons: [] },
      { id: 'mod-5', number: 5, title: 'Módulo 5: Anotación y Documentación', description: 'Textos, cotas, directrices y tablas.', duration: 4, order: 5, lessons: [] },
      { id: 'mod-6', number: 6, title: 'Módulo 6: Layouts e Impresión', description: 'Espacio papel, viewports y publicación PDF.', duration: 3, order: 6, lessons: [] },
      { id: 'mod-7', number: 7, title: 'Módulo 7: Colaboración y Flujos Web', description: 'Activity Insights, Trace y AutoCAD Web.', duration: 3, order: 7, lessons: [] },
    ],
  },

  // 2. AUTOCAD 3D 2026
  {
    id: 'autocad-3d-2026',
    slug: 'autocad-3d-2026',
    version: '2026',
    software: 'AutoCAD 2026',
    title: 'AutoCAD 3D 2026 - Modelado Tridimensional',
    subtitle: 'Domina el modelado 3D con las nuevas herramientas de AutoCAD 2026',
    category: 'AutoCAD',
    level: 'Intermedio',
    duration: 16,
    sessions: 4,
    description: `Modelado 3D avanzado con AutoCAD 2026. Aprende a crear sólidos, superficies y mallas complejas, y a generar renders fotorrealistas.`,
    objectives: [
      'Dominar el espacio de trabajo 3D',
      'Crear y editar sólidos primitivos y complejos',
      'Trabajar con superficies y mallas',
      'Generar vistas y secciones 3D',
      'Aplicar materiales, luces y renderizar',
    ],
    prerequisites: ['AutoCAD 2D Básico'],
    certification: 'Autodesk Certified Professional - AutoCAD 3D',
    instructor: 'Ing. [Nombre] - ACI',
    price: 199,
    priceVEF: 7000,
    image: '/images/courses/autocad-3d-2026.jpg',
    thumbnail: '/images/courses/autocad-3d-2026-thumb.jpg',
    featured: false,
    popular: false,
    enrollmentCount: 0,
    rating: 0,
    reviewsCount: 0,
    skills: ['AutoCAD 3D', 'Modelado 3D', 'Rendering'],
    tags: ['AutoCAD', '2026', '3D', 'Modelado'],
    lastUpdated: '2026-01-15T00:00:00Z',
    releaseDate: '2025-11-01T00:00:00Z',
    syllabus: [
      { id: 'ac3d-mod-1', number: 1, title: 'Módulo 1: Entorno 3D y Coordenadas', description: 'UCS, Vistas y Navegación 3D.', duration: 3, order: 1, lessons: [] },
      { id: 'ac3d-mod-2', number: 2, title: 'Módulo 2: Modelado de Sólidos', description: 'Extrusión, Revolución, Barrido y Operaciones Booleanas.', duration: 5, order: 2, lessons: [] },
      { id: 'ac3d-mod-3', number: 3, title: 'Módulo 3: Superficies y Mallas', description: 'Modelado orgánico y superficies complejas.', duration: 4, order: 3, lessons: [] },
      { id: 'ac3d-mod-4', number: 4, title: 'Módulo 4: Visualización y Render', description: 'Materiales, Luces, Cámaras y Renderizado.', duration: 4, order: 4, lessons: [] },
    ],
  },

  // 3. REVIT ARCHITECTURE 2026
  {
    id: 'revit-architecture-2026',
    slug: 'revit-architecture-2026',
    version: '2026',
    software: 'Revit 2026',
    title: 'Revit Architecture 2026 - BIM Avanzado',
    subtitle: 'Metodología BIM con las últimas innovaciones de Revit 2026',
    category: 'Revit',
    level: 'Intermedio',
    duration: 40,
    sessions: 10,
    description: `Curso completo de Revit Architecture 2026. Domina el modelado BIM arquitectónico, desde el concepto hasta la documentación constructiva.`,
    objectives: [
      'Entender la metodología BIM',
      'Modelar elementos arquitectónicos (muros, suelos, techos)',
      'Crear familias paramétricas básicas',
      'Generar planos, cortes y alzados automáticos',
      'Colaborar en la nube con Autodesk Docs',
    ],
    prerequisites: ['Conocimientos de arquitectura', 'AutoCAD básico'],
    certification: 'Autodesk Certified Professional - Revit Architecture',
    instructor: 'Arq. [Nombre] - Revit Expert',
    price: 499,
    priceVEF: 18000,
    image: '/images/courses/revit-2026-architecture.jpg',
    thumbnail: '/images/courses/revit-2026-arch-thumb.jpg',
    featured: true,
    popular: true,
    enrollmentCount: 0,
    rating: 0,
    reviewsCount: 0,
    skills: ['Revit', 'BIM', 'Arquitectura'],
    tags: ['Revit', '2026', 'BIM', 'Arquitectura'],
    lastUpdated: '2026-01-15T00:00:00Z',
    releaseDate: '2025-11-01T00:00:00Z',
    syllabus: [
      { id: 'rvt-arch-mod-1', number: 1, title: 'Módulo 1: Introducción a BIM y Revit', description: 'Conceptos BIM, Interfaz y Configuración.', duration: 4, order: 1, lessons: [] },
      { id: 'rvt-arch-mod-2', number: 2, title: 'Módulo 2: Modelado Básico', description: 'Muros, Puertas, Ventanas y Suelos.', duration: 8, order: 2, lessons: [] },
      { id: 'rvt-arch-mod-3', number: 3, title: 'Módulo 3: Circulación y Estructura', description: 'Escaleras, Barandillas, Pilares y Cubiertas.', duration: 8, order: 3, lessons: [] },
      { id: 'rvt-arch-mod-4', number: 4, title: 'Módulo 4: Documentación', description: 'Cotas, Etiquetas, Tablas de Planificación y Planos.', duration: 10, order: 4, lessons: [] },
      { id: 'rvt-arch-mod-5', number: 5, title: 'Módulo 5: Visualización y Familia', description: 'Renderizado básico y creación de familias simples.', duration: 10, order: 5, lessons: [] },
    ],
  },

  // 4. REVIT STRUCTURE 2026
  {
    id: 'revit-structure-2026',
    slug: 'revit-structure-2026',
    version: '2026',
    software: 'Revit 2026',
    title: 'Revit Structure 2026 - BIM Estructural',
    subtitle: 'Diseño y detallado estructural BIM con Revit 2026',
    category: 'Revit',
    level: 'Avanzado',
    duration: 30,
    sessions: 8,
    description: `Especialización en modelado estructural con Revit 2026. Aprende a modelar hormigón armado, acero estructural y cimentaciones.`,
    objectives: [
      'Modelar sistemas estructurales de hormigón y acero',
      'Colocar armaduras (Rebar) y conexiones',
      'Integrar con Robot Structural Analysis',
      'Generar planos de detalle estructural',
    ],
    prerequisites: ['Revit Architecture Básico', 'Conocimientos de Estructuras'],
    certification: 'Autodesk Certified Professional - Revit Structure',
    instructor: 'Ing. [Nombre] - Structural Engineer',
    price: 499,
    priceVEF: 18000,
    image: '/images/courses/revit-2026-structure.jpg',
    thumbnail: '/images/courses/revit-2026-struct-thumb.jpg',
    featured: false,
    popular: false,
    enrollmentCount: 0,
    rating: 0,
    reviewsCount: 0,
    skills: ['Revit', 'BIM', 'Estructuras', 'Ingeniería'],
    tags: ['Revit', '2026', 'BIM', 'Estructuras'],
    lastUpdated: '2026-01-15T00:00:00Z',
    releaseDate: '2025-11-01T00:00:00Z',
    syllabus: [
      { id: 'rvt-str-mod-1', number: 1, title: 'Módulo 1: Configuración Estructural', description: 'Plantillas, Niveles y Rejillas Estructurales.', duration: 4, order: 1, lessons: [] },
      { id: 'rvt-str-mod-2', number: 2, title: 'Módulo 2: Cimentaciones y Pilares', description: 'Zapatas, Losas y Columnas Estructurales.', duration: 6, order: 2, lessons: [] },
      { id: 'rvt-str-mod-3', number: 3, title: 'Módulo 3: Vigas y Sistemas de Vigas', description: 'Entramados de acero y hormigón.', duration: 6, order: 3, lessons: [] },
      { id: 'rvt-str-mod-4', number: 4, title: 'Módulo 4: Refuerzo (Rebar)', description: 'Armado de elementos de hormigón.', duration: 8, order: 4, lessons: [] },
      { id: 'rvt-str-mod-5', number: 5, title: 'Módulo 5: Documentación Estructural', description: 'Planos de detalle y tablas de cantidades.', duration: 6, order: 5, lessons: [] },
    ],
  },

  // 5. REVIT MEP 2026
  {
    id: 'revit-mep-2026',
    slug: 'revit-mep-2026',
    version: '2026',
    software: 'Revit 2026',
    title: 'Revit MEP 2026 - Instalaciones BIM',
    subtitle: 'Diseño de instalaciones mecánicas, eléctricas y sanitarias',
    category: 'Revit',
    level: 'Avanzado',
    duration: 40,
    sessions: 10,
    description: `Curso integral de Revit MEP 2026. Aprende a modelar, coordinar y documentar sistemas HVAC, eléctricos y sanitarios.`,
    objectives: [
      'Configurar proyectos MEP',
      'Modelar sistemas HVAC (Ductos)',
      'Modelar sistemas de Fontanería (Piping)',
      'Modelar sistemas Eléctricos',
      'Detección de interferencias básica',
    ],
    prerequisites: ['Revit Architecture Básico', 'Conocimientos de Instalaciones'],
    certification: 'Autodesk Certified Professional - Revit MEP',
    instructor: 'Ing. [Nombre] - MEP Specialist',
    price: 499,
    priceVEF: 18000,
    image: '/images/courses/revit-2026-mep.jpg',
    thumbnail: '/images/courses/revit-2026-mep-thumb.jpg',
    featured: false,
    popular: false,
    enrollmentCount: 0,
    rating: 0,
    reviewsCount: 0,
    skills: ['Revit', 'BIM', 'MEP', 'Instalaciones'],
    tags: ['Revit', '2026', 'MEP', 'Instalaciones'],
    lastUpdated: '2026-01-15T00:00:00Z',
    releaseDate: '2025-11-01T00:00:00Z',
    syllabus: [
      { id: 'rvt-mep-mod-1', number: 1, title: 'Módulo 1: Introducción a MEP y Vinculación', description: 'Interfaz MEP, Linking Architecture.', duration: 4, order: 1, lessons: [] },
      { id: 'rvt-mep-mod-2', number: 2, title: 'Módulo 2: HVAC (Mecánica)', description: 'Espacios, Zonas, Ductos y Equipos Mecánicos.', duration: 10, order: 2, lessons: [] },
      { id: 'rvt-mep-mod-3', number: 3, title: 'Módulo 3: Fontanería (Plumbing)', description: 'Tuberías, Accesorios y Equipos Sanitarios.', duration: 10, order: 3, lessons: [] },
      { id: 'rvt-mep-mod-4', number: 4, title: 'Módulo 4: Electricidad', description: 'Iluminación, Potencia, Circuitos y Paneles.', duration: 10, order: 4, lessons: [] },
      { id: 'rvt-mep-mod-5', number: 5, title: 'Módulo 5: Documentación y Coordinación', description: 'Etiquetas, Tablas y Detección de Interferencias.', duration: 6, order: 5, lessons: [] },
    ],
  },

  // 6. CIVIL 3D 2026
  {
    id: 'civil3d-2026',
    slug: 'civil3d-2026',
    version: '2026',
    software: 'Civil 3D 2026',
    title: 'Civil 3D 2026 - Diseño de Infraestructura',
    subtitle: 'Diseño civil, topografía y vialidad con Civil 3D 2026',
    category: 'Civil3D',
    level: 'Avanzado',
    duration: 40,
    sessions: 10,
    description: `Domina el diseño de infraestructura civil con Civil 3D 2026. Desde la importación de puntos topográficos hasta el diseño de carreteras y redes de tuberías.`,
    objectives: [
      'Gestionar puntos y grupos de puntos',
      'Crear y analizar superficies de terreno',
      'Diseñar alineamientos y perfiles longitudinales',
      'Crear corredores viales (Corridors)',
      'Calcular volúmenes de movimiento de tierras',
    ],
    prerequisites: ['AutoCAD 2D Avanzado', 'Topografía/Ingeniería Civil'],
    certification: 'Autodesk Certified Professional - Civil 3D',
    instructor: 'Ing. [Nombre] - Civil Engineer',
    price: 499,
    priceVEF: 18000,
    image: '/images/courses/civil3d-2026.jpg',
    thumbnail: '/images/courses/civil3d-2026-thumb.jpg',
    featured: true,
    popular: true,
    enrollmentCount: 0,
    rating: 0,
    reviewsCount: 0,
    skills: ['Civil 3D', 'Ingeniería Civil', 'Topografía'],
    tags: ['Civil3D', '2026', 'Civil', 'Vialidad'],
    lastUpdated: '2026-01-15T00:00:00Z',
    releaseDate: '2025-11-01T00:00:00Z',
    syllabus: [
      { id: 'c3d-mod-1', number: 1, title: 'Módulo 1: Puntos y Superficies', description: 'Importación de datos y modelado digital del terreno.', duration: 8, order: 1, lessons: [] },
      { id: 'c3d-mod-2', number: 2, title: 'Módulo 2: Alineamientos y Perfiles', description: 'Diseño geométrico horizontal y vertical.', duration: 8, order: 2, lessons: [] },
      { id: 'c3d-mod-3', number: 3, title: 'Módulo 3: Ensamblajes y Corredores', description: 'Secciones típicas y modelado de obra lineal.', duration: 8, order: 3, lessons: [] },
      { id: 'c3d-mod-4', number: 4, title: 'Módulo 4: Secciones Transversales y Volúmenes', description: 'Cómputo de materiales y movimiento de tierras.', duration: 8, order: 4, lessons: [] },
      { id: 'c3d-mod-5', number: 5, title: 'Módulo 5: Redes de Tuberías y Planos', description: 'Pipe Networks y producción de planos (Plan Production).', duration: 8, order: 5, lessons: [] },
    ],
  },

  // 7. AUTOCAD PLANT 3D 2026
  {
    id: 'plant3d-2026',
    slug: 'plant3d-2026',
    version: '2026',
    software: 'AutoCAD Plant 3D 2026',
    title: 'AutoCAD Plant 3D 2026 - Diseño de Plantas',
    subtitle: 'Diseño de plantas industriales, P&ID y tuberías 3D',
    category: 'Plant3D',
    level: 'Especializado',
    duration: 32,
    sessions: 8,
    description: `Curso especializado en diseño de plantas industriales. Aprende a crear diagramas P&ID inteligentes y modelos de tuberías 3D con AutoCAD Plant 3D 2026.`,
    objectives: [
      'Configurar proyectos de Plant 3D',
      'Crear diagramas P&ID inteligentes',
      'Modelar estructuras, equipos y tuberías en 3D',
      'Generar planos isométricos y ortogonales',
      'Gestionar especificaciones de tuberías',
    ],
    prerequisites: ['AutoCAD 3D', 'Conocimientos de Piping/Procesos'],
    certification: 'Plant Design Specialist',
    instructor: 'Ing. [Nombre] - Piping Designer',
    price: 499,
    priceVEF: 18000,
    image: '/images/courses/plant3d-2026.jpg',
    thumbnail: '/images/courses/plant3d-2026-thumb.jpg',
    featured: false,
    popular: false,
    enrollmentCount: 0,
    rating: 0,
    reviewsCount: 0,
    skills: ['Plant 3D', 'Piping', 'P&ID', 'Industrial'],
    tags: ['Plant3D', '2026', 'Piping', 'Industrial'],
    lastUpdated: '2026-01-15T00:00:00Z',
    releaseDate: '2025-11-01T00:00:00Z',
    syllabus: [
      { id: 'p3d-mod-1', number: 1, title: 'Módulo 1: Configuración de Proyecto y P&ID', description: 'Project Manager y creación de diagramas de flujo.', duration: 6, order: 1, lessons: [] },
      { id: 'p3d-mod-2', number: 2, title: 'Módulo 2: Modelado de Estructuras y Equipos', description: 'Grids, Steel y Equipment Modeling.', duration: 6, order: 2, lessons: [] },
      { id: 'p3d-mod-3', number: 3, title: 'Módulo 3: Diseño de Tuberías 3D', description: 'Routing de tuberías, válvulas y soportes.', duration: 8, order: 3, lessons: [] },
      { id: 'p3d-mod-4', number: 4, title: 'Módulo 4: Isométricos y Ortogonales', description: 'Generación automática de planos de fabricación.', duration: 6, order: 4, lessons: [] },
      { id: 'p3d-mod-5', number: 5, title: 'Módulo 5: Gestión de Datos y Specs', description: 'Data Manager y Spec Editor.', duration: 6, order: 5, lessons: [] },
    ],
  },

  // 8. INVENTOR NASTRAN 2026
  {
    id: 'inventor-nastran-2026',
    slug: 'inventor-nastran-2026',
    version: '2026',
    software: 'Inventor Nastran 2026',
    title: 'Inventor Nastran 2026 - Simulación FEA',
    subtitle: 'Análisis de elementos finitos y simulación avanzada',
    category: 'Inventor',
    level: 'Especializado',
    duration: 24,
    sessions: 6,
    description: `Curso de simulación y análisis de elementos finitos (FEA) integrado en Inventor. Aprende a validar tus diseños mecánicos antes de fabricar.`,
    objectives: [
      'Entender los fundamentos de FEA',
      'Realizar análisis estáticos lineales',
      'Analizar ensamblajes y contactos',
      'Realizar análisis modales y de pandeo',
      'Interpretar resultados y optimizar diseños',
    ],
    prerequisites: ['Autodesk Inventor Avanzado', 'Resistencia de Materiales'],
    certification: 'Simulation Specialist',
    instructor: 'Ing. [Nombre] - FEA Analyst',
    price: 599,
    priceVEF: 22000,
    image: '/images/courses/inventor-nastran-2026.jpg',
    thumbnail: '/images/courses/inventor-nastran-2026-thumb.jpg',
    featured: false,
    popular: false,
    enrollmentCount: 0,
    rating: 0,
    reviewsCount: 0,
    skills: ['Nastran', 'FEA', 'Simulación', 'Inventor'],
    tags: ['Inventor', 'Nastran', '2026', 'Simulación'],
    lastUpdated: '2026-01-15T00:00:00Z',
    releaseDate: '2025-11-01T00:00:00Z',
    syllabus: [
      { id: 'nst-mod-1', number: 1, title: 'Módulo 1: Introducción a FEA y Nastran', description: 'Conceptos básicos, interfaz y mallado.', duration: 4, order: 1, lessons: [] },
      { id: 'nst-mod-2', number: 2, title: 'Módulo 2: Análisis Estático Lineal', description: 'Cargas, restricciones y análisis de piezas.', duration: 6, order: 2, lessons: [] },
      { id: 'nst-mod-3', number: 3, title: 'Módulo 3: Análisis de Ensamblajes', description: 'Tipos de contacto y conectores.', duration: 6, order: 3, lessons: [] },
      { id: 'nst-mod-4', number: 4, title: 'Módulo 4: Análisis Avanzados', description: 'Modal, Pandeo y Fatiga.', duration: 4, order: 4, lessons: [] },
      { id: 'nst-mod-5', number: 5, title: 'Módulo 5: Interpretación y Reportes', description: 'Convergencia, validación y generación de informes.', duration: 4, order: 5, lessons: [] },
    ],
  },
];
